general.import = ["/home/nain/.config/alacritty/themes/gruvboxDark.toml"]

[env]
WINIT_X11_SCALE_FACTOR = "1"

[window]
padding = { x = 10, y = 10}
dynamic_padding = true

[font]
size = 12 

[font.normal]
family = "Iosevka"


