[colors.primary]
"foreground" = "#bebebe"
"background" = "#0d0d0d"
bright_foreground = "#ffffff"

[colors.normal]
black = "#000000"
red = "#be3030"
green = "#61be2e"
yellow = "#c0912f"
blue = "#2f53bf"
magenta = "#bf31bf"
cyan = "#30bebe"
white = "#7f7f7f"

[colors.bright]
black = "#3f3f3f"
red = "#be5f5f"
green = "#7fbf60"
yellow = "#c0b161"
blue = "#5f77c0"
magenta = "#bf60bf"
cyan = "#60beb6"
white = "#bebebe"
